version: '3.6'
services:

    mongo:
        image: mongo:3.4
#       image: mongo:3 MONGO 3.6 HAS INCOMPATIBILITY WITH $pushAll
        restart: always
        env_file: 
            - ./.env
        networks: 
            - learninglocker-network
        volumes:
            - mongodb-volume:/data/db
        ports:
            - "27017:${MONGO_PORT}"

    redis:
        image: redis:4-alpine
        restart: always
        env_file: 
            - ./.env
        networks: 
            - learninglocker-network
        ports:
            - "6379:${REDIS_PORT}"

    xapi:
        build: ./xapi
        restart: always
        env_file: 
            - ./.env
        depends_on:
            - mongo
            - redis
        networks: 
            - learninglocker-network

    webapp:
        build: ./app
        env_file: 
            - ./.env
        command: "./entrypoint-webapp.sh"
        restart: always
        depends_on:
            - mongo
            - redis
        networks: 
            - learninglocker-network
        volumes:
            - ll-volume:/opt/learninglocker/storage

    worker:
        build: ./app
        env_file: 
            - ./.env
        command: "./entrypoint-worker.sh"
        restart: always
        depends_on:
            - mongo
            - redis
        networks: 
            - learninglocker-network
        volumes:
            - ll-volume:/opt/learninglocker/storage

    nginx:
        build: ./nginx
        env_file: 
            - ./.env
        restart: always
        depends_on:
            - webapp
            - xapi
        networks: 
            - learninglocker-network
        ports:
            - "80:${DOMAIN_PORT}"

volumes:
    mongodb-volume:
    ll-volume:
            
networks:
    learninglocker-network:
        driver: bridge
