version: '3.6'
services:

    mongo:
        image: mongo:3.4
#       image: mongo:3 MONGO 3.6 HAS INCOMPATIBILITY WITH $pushAll
        restart: always
        env_file: 
            - ./.env
        networks: 
            - learninglocker-network
        volumes:
            - "${DATA_LOCATION}/mongo:/data/db"

    redis:
        image: redis:4-alpine
        restart: unless-stopped

    xapi:
        image: learninglocker/xapi-service:latest
        restart: unless-stopped
        environment:
            - MONGO_URL
            - REDIS_URL
        depends_on:
            - mongo
            - redis

    api:
        image: jgasparetti/learninglocker2-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node api/dist/server"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"

    ui:
        image: jgasparetti/learninglocker2-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "./entrypoint-ui.sh"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
            - api
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"

    worker:
        image: jgasparetti/learninglocker2-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node worker/dist/server"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"

    nginx:
        image: jgasparetti/learninglocker2-nginx:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
        restart: unless-stopped
        depends_on:
            - ui
            - xapi
        ports:
            - "443:443"
            - "80:80"

